---
- name: Rollback
  hosts: srv1.mad.lab
  gather_facts: no
  vars_prompt:
    - name: "rollback"
      prompt: "01-empty, 02-cisco-cnik, 03-before-init (1.20)"
      default: "03"
      private: no
  tasks:
    - name: rollback
      command: "{{item}}"
      with_items:
        - virsh snapshot-revert --snapshotname {{rollback}} --domain kb-node1
        - virsh snapshot-revert --snapshotname {{rollback}} --domain kb-node2
        - virsh snapshot-revert --snapshotname {{rollback}} --domain kb-node3
        - virsh snapshot-revert --snapshotname {{rollback}} --domain kb-node4
        - virsh start kb-node1
        - virsh start kb-node2
        - virsh start kb-node3
        - virsh start kb-node4
