---
- name: Rollback
  hosts: srv1.mad.lab
  gather_facts: no
  tasks:
    - name: rollback
      command: "{{item}}"
      with_items:
        - virsh snapshot-revert --snapshotname 01 --domain kb-node1
        - virsh snapshot-revert --snapshotname 01 --domain kb-node2
        - virsh snapshot-revert --snapshotname 01 --domain kb-node3
        - virsh snapshot-revert --snapshotname 01 --domain kb-node4
        - virsh start kb-node1
        - virsh start kb-node2
        - virsh start kb-node3
        - virsh start kb-node4

