---
- name: Rollback
  hosts: srv1.mad.lab
  gather_facts: no
  vars_prompt:
    - name: "rollback"
      prompt: "01-empty, 02 docker installed, 03-cluster init(before cni), 04-cisco-cni-ok"
      default: "02"
      private: no
  tasks:
    - name: rollback
      command: "{{item}}"
      with_items:
        - virsh snapshot-revert --snapshotname {{rollback}} --domain kube-1
        - virsh snapshot-revert --snapshotname {{rollback}} --domain kube-2
        - virsh snapshot-revert --snapshotname {{rollback}} --domain kube-3
        - virsh snapshot-revert --snapshotname {{rollback}} --domain kube-4
        - virsh start kube-1
        - virsh start kube-2
        - virsh start kube-3
        - virsh start kube-4

