---
- name: DEPLOY CENTOS
  hosts: kb-controller
  gather_facts: no
  vars_prompt:
    - name: "replicas"
      prompt: "replicas"
      private: no
  tasks:
    - name: Copy yaml
      copy:
        src: /root/kubernetes/deploy-centos.yml
        dest: /root/deploy-centos.yml
    - name: Deploying
      command: "{{item}}"
      with_items:
#        - kubectl create ns {{namespace}}
        - kubectl apply -f /root/deploy-centos.yml
        - kubectl scale --replicas={{replicas}} -f /root/deploy-centos.yml
