---
- name: DEPLOY WEB-SERVER
  hosts: kb-controller
  gather_facts: no
  vars_prompt:
    - name: "namespace"
      prompt: "namespace"
      private: no
  tasks:
    - name: Deploy project
      command: "{{item}}"
      with_items:
        - kubectl delete deployment web-server -n {{namespace}}
        - kubectl delete ns {{namespace}}
