---
- name: DEPLOY WEB-SERVER
  hosts: kb-controller
  gather_facts: no
  vars_prompt:
    - name: "namespace"
      prompt: "namespace"
      private: no
    - name: "replicas"
      prompt: "replicas"
      private: no
  tasks:
    - name: Copy deployment-nginx.yaml
      copy:
        src: /root/kubernetes/deployment-nginx.yaml
        dest: /root/deployment-nginx.yaml
    - name: Deploy project
      command: "{{item}}"
      with_items:
        - kubectl create ns {{namespace}}
        - kubectl -n {{namespace}} apply -f /root/deployment-nginx.yaml
        - kubectl expose deployment web-server --type="LoadBalancer" -n {{namespace}}
        - kubectl scale --replicas={{replicas}} -n {{namespace}} -f /tmp/deployment-nginx.yaml
