---
- name: DEPLOY WEB-SERVER
  hosts: kb-controller
  gather_facts: no
  vars_prompt:
    - name: "namespace"
      prompt: "namespace"
      private: no
    - name: "replicas"
      prompt: "replicas"
      private: no
  tasks:
    - name: Copy anginx.yaml
      copy:
        src: /root/kubernetes/deploy-nginx.yml
        dest: /root/deploy-nginx.yml
    - name: Deploy nginx
      command: "{{item}}"
      with_items:
        - kubectl create ns {{namespace}}
        - kubectl -n {{namespace}} apply -f /root/deploy-nginx.yml
        - kubectl expose deployment web-server --type="LoadBalancer" -n {{namespace}}
        - kubectl scale --replicas={{replicas}} -n {{namespace}} -f /root/deploy-nginx.yml
