---
- name: INSTALL ISTIO
  hosts: controller
  tasks:
    - name: Download
      get_url:
        url: http://registry.mad.lab/istio-1.3.4.tar
        dest: /root/istio-1.3.4.tar
    - name: Unpackage
      command: tar -xvf istio-1.3.4.tar
    - name: Install istio CRDs
      command: "for i in /root/istio-1.3.4/install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done"
    - name: Install ISTIO
      command: "kubectl apply -f /root/istio-1.3.4/install/kubernetes/istio-demo.yaml"

