---
- name: CLUSTER INIT
  hosts: kb-controller
  tasks:
    - name: Kubernetes cluster initialization cir 1.2.192.0/23 (1.2.128.11)
      command: "kubeadm init --pod-network-cidr=1.2.192.0/23 --apiserver-advertise-address=1.2.128.11"
    - name: Variables entorno
      command: "{{item}}"
      with_items:
        - mkdir -p /root/.kube
        - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - chown 0:0 /root/.kube/config
    - name: Get token
      shell: kubeadm token create --print-join-command
      register: kubeadm_token
    - debug: msg="{{ kubeadm_token.stdout }}"
