apiVersion: aci.snat/v1
kind: SnatPolicy
metadata:
  name: my-snat-name
spec:
  selector:
    namespace: testns
    labels:      my-snat-label: backend-apps
  snatIp:
    - 10.20.30.40

apiVersion: v1
kind: Podmetadata:
  name: busybox
  labels:
    my-snat-label: backend-apps
    namespace: Default
spec:
  containers:
    - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    restartPolicy: Always
