apiVersion: aci.snat/v1
kind: SnatPolicy
metadata:
  name: my-snat-name
spec:
  selector:
    namespace: testns
    labels:
      my-snat-label: backend-apps
  snatIp:
    - 10.20.30.40
apiVersion: v1
kind: Namespace
metadata:
  labels:
    my-snat-label: backend-apps
  name: aitor
spec:
  finalizers:
    - kubernetes
